import pandas as pd     # Pandas library used to load, inspect, clean, transform, and analyze tabular data
from sklearn.model_selection import train_test_split     # Function to split the dataset into training and testing sets
from sklearn.compose import ColumnTransformer     # Class to apply different transformations to different columns of the dataset

from sklearn.preprocessing import StandardScaler, OneHotEncoder
# StandardScaler: Shifts data to have a mean of 0 and a standard deviation of 1
# OneHotEncoder: Converts nominal, unordered text labels into unique binary columns

from config import DATA_PATH    # Import the path to the dataset from the config file

def load_data():
    df = pd.read_csv(DATA_PATH)     # Create a function to read the csv file
    return df   # Returns a pandas dataframe



def clean_data(df):       # Create a function to clean data
    df = df.copy()  # Copy the dataframe so the preprocessing tasks won't alter the original dataset

    df.drop(
        'customerID',axis = 1,  # Remove the 'customerID' column as it does not bring classification importance.
        inplace = True  # Make changes to the dataframe as well
    )

    df["TotalCharges"] = pd.to_numeric(     # Convert 'TotalCharges' column to ensure it is a numeric type
        df["TotalCharges"],
        errors="coerce"     # Forces the invalid or unparseable values to be replaced with missing values or NaN
    )

    df.dropna(
        inplace = True  # Remove missing rows
    )

    return df   # Return the cleaned data



def split_data(df):     # Create a function to split the data into features(X) and class(y)
    X = df.drop(    
        'Churn',    # Define X as the features
        axis = 1
    )

    y = df["Churn"].map(    # Define y as the class
        {
            "No":0, # Map numerical value 0 or 1 to 'No' or 'Yes' respectively
            "Yes":1
        }
    )

    return X,y  # return X and y both dataframes



def train_test_data(X,y):       # Create a function to split training and testing data
    return train_test_split(
        X,
        y,
        test_size=0.2,  # 20% data to be used as testing data and 80% to be used as training data.
        random_state=42,    # ensure reproducibility
        stratify=y  # Ensures training and testing datasets have the exact same proportion of class labels as the original
    )



def build_preprocessor(X):  # Create a function that processes the training data
    numerical_features = X.select_dtypes(
        include=["int64","float64"]         # Store all numerical data types in 'numerical_features'
    ).columns

    categorical_features = X.select_dtypes(
        include=["object"]                  # Store all object data tyoes in 'categorical_features'
    ).columns


    preprocessor = ColumnTransformer(  # Different columns to be transformed separately and the features generated by each transformer will be concatenated to form a single feature space.


        transformers = [
            (
                "num",      # Numerical Transformation
                StandardScaler(),   # Standardize numerical features to improve model performance
                numerical_features
            ),

            (
                "cat",  # Categorical Transformation
                OneHotEncoder(      # Convert categorical values into numerics
                    handle_unknown="ignore",    # Ignore unseen categories during prediction
                ),
                categorical_features
            )
        ]
    )
    return preprocessor     # Return the processed dataframe